/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutTab: typeof import('./src/components/features/settings/AboutTab.vue')['default']
    AccountTab: typeof import('./src/components/features/settings/AccountTab.vue')['default']
    AgentPanel: typeof import('./src/components/panels/AgentPanel.vue')['default']
    AIModelTab: typeof import('./src/components/features/settings/AIModelTab.vue')['default']
    BubbleToolbar: typeof import('./src/components/features/editor/BubbleToolbar.vue')['default']
    DeleteConfirmDialog: typeof import('./src/components/features/settings/DeleteConfirmDialog.vue')['default']
    EditorContextMenu: typeof import('./src/components/features/editor/EditorContextMenu.vue')['default']
    EditorStatusBar: typeof import('./src/components/features/editor/EditorStatusBar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTree: typeof import('element-plus/es')['ElTree']
    EmbeddingConfig: typeof import('./src/components/features/settings/EmbeddingConfig.vue')['default']
    FindReplaceBar: typeof import('./src/components/features/editor/FindReplaceBar.vue')['default']
    GeneralTab: typeof import('./src/components/features/settings/GeneralTab.vue')['default']
    IconRail: typeof import('./src/components/layout/IconRail.vue')['default']
    InlineInput: typeof import('./src/components/features/note-tree/InlineInput.vue')['default']
    LeftPanel: typeof import('./src/components/panels/LeftPanel.vue')['default']
    NoteTree: typeof import('./src/components/features/note-tree/NoteTree.vue')['default']
    ProfileEditor: typeof import('./src/components/features/settings/ProfileEditor.vue')['default']
    ProfileEmptyState: typeof import('./src/components/features/settings/ProfileEmptyState.vue')['default']
    ProfileList: typeof import('./src/components/features/settings/ProfileList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./src/components/features/search-panel/SearchPanel.vue')['default']
    SettingsDialog: typeof import('./src/components/features/settings/SettingsDialog.vue')['default']
    StatusBar: typeof import('./src/components/layout/StatusBar.vue')['default']
    TiptapEditor: typeof import('./src/components/features/editor/TiptapEditor.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
    TrashView: typeof import('./src/components/features/trash-view/TrashView.vue')['default']
  }
}
